GET http://localhost:3030/getUsers
###
POST http://localhost:3030/createUser
Content-Type: application/json

{
    "firstName": "Caasdtalin",
    "lastName": "asd",
    "email": "radoi.catalin88@gmail.com",
    "password": "123456"
}
###
DELETE http://localhost:3030/deleteUser/66201a12166fdd621354f362
###
POST http://localhost:3030/login
Content-Type: application/json

{
   "email": "radoi.catalin88@gmail.com",
   "password": "123456"
}
###
POST http://localhost:3030/expenses/addCategory
Content-Type: application/json

{
    "categoryName": "fasulla da cancellare",
        "color": "#4586d1"

}
###
GET http://localhost:3030/expenses/getCategories
###
DELETE http://localhost:3030/expenses/deleteCategory/6624f9dc3fac85accfbba713
###
POST http://localhost:3030/expenses/addExpense
Content-Type: application/json

{
    "amount": 1257,
    "category": "6624f46d64f0decd527664fc",
    "description": "Bolletta gas",
    "opDate": "2024-04-22",
    "userId": "662017fb3f038f140eac7956"

}
###
GET http://localhost:3030/expenses/getTotalExpenses
###
GET http://localhost:3030/expenses/getExpensesByDate
Content-Type: application/json

{
    "fromDate": 2024-04-24,
    "toDate": 2024-04-26,
}
###
DELETE http://localhost:3030/expenses/deleteExpense/6626b0caa72f06cdbf23df7a